_wandb:
    value:
        cli_version: 0.24.0
        e:
            3mc0ydyw2aafx02hldw0gxfb3y62kzsi:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "28991029248"
                args:
                    - config/sort_alpha.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "392523427840"
                email: sahan@dickinson.edu
                executable: /opt/anaconda3/envs/comp560/bin/python
                git:
                    commit: b8c606410c498f29e45d746b7476cd846ca815fb
                    remote: https://github.com/niloy-saha-123/comp560-niloy.git
                host: MacBook-Pro-429.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/niloysaha/IdeaProjects/comp560/comp560-niloy/sort-alpha/../../comp560-nanoGPT/train.py
                python: CPython 3.11.14
                root: /Users/niloysaha/IdeaProjects/comp560/comp560-niloy/sort-alpha
                startedAt: "2026-02-04T23:25:13.467186Z"
                writerId: 3mc0ydyw2aafx02hldw0gxfb3y62kzsi
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 64
compile:
    value: false
dataset:
    value: sort
decay_lr:
    value: true
device:
    value: mps
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 250
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out/sort-alpha
wandb_log:
    value: true
wandb_project:
    value: comp560-sort
wandb_run_name:
    value: sort-alpha-basic
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
