_wandb:
    value:
        cli_version: 0.24.0
        e:
            di3xv0008vb1m25tawg69pbvkmkbe2yt:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "25769803776"
                args:
                    - config/basic.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "388759498752"
                email: sahan@dickinson.edu
                executable: /opt/anaconda3/envs/comp560/bin/python
                git:
                    commit: 844ca20a55d97d3bf41f2fe75b9f598241fde129
                    remote: https://github.com/niloy-saha-123/comp560-niloy.git
                host: MacBook-Pro-429.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/niloysaha/IdeaProjects/comp560/comp560-niloy/unscramble/../../comp560-nanoGPT/train.py
                python: CPython 3.11.14
                root: /Users/niloysaha/IdeaProjects/comp560/comp560-niloy/unscramble
                startedAt: "2026-02-04T22:39:12.549751Z"
                writerId: di3xv0008vb1m25tawg69pbvkmkbe2yt
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 64
compile:
    value: false
dataset:
    value: basic
decay_lr:
    value: true
device:
    value: mps
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 50
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 1
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 0.0001
n_embd:
    value: 120
n_head:
    value: 3
n_layer:
    value: 3
out_dir:
    value: out/basic
wandb_log:
    value: true
wandb_project:
    value: comp560-unscramble
wandb_run_name:
    value: unscramble-basic
warmup_iters:
    value: 0
weight_decay:
    value: 0.1
